```{R}
x=as.POSIXct("2021-02-25 22:00:23","%Y-%m-%d %H:%M:%S")
y=as.POSIXct("2021-02-26 23:00:23","%Y-%m-%d %H:%M:%S")
difftime(y,x,units = "secs")
```
```{R}
x = as.POSIXct("2021-02-25 22:00:23", format="%Y-%m-%d %H:%M:%S")
y = as.POSIXct("2021-02-26 01:00:23", format="%Y-%m-%d %H:%M:%S")

diff_hours = difftime(y, x, units = "hours")
diff_hours
```
```{R}
a=c(1,2,3)
a
names(a)=c("a","b","c")
a
a[2]
unname(a[2])
```

```{r}
x=c(1,2,3,4)
y=c(5,6,7,8)
x*y
y=c(5,6,7,4,3,2,1)
x*y
2*x+1
```

```{r}
x=c(3,1,2,1,1,NA)
names(x)=c("A","B","C","D","E","F")
x
x==1
which(x==1)
unique(x)
sort(x)
order(x,decreasing=T,na.last=T)
```

練習

```{r}
x=read.csv("Week 2/finalscore_exercise.csv",sep=",",header=T)
hw=x[,2]
mid=x[,3]
final=x[,4]
total=hw*0.3+mid*0.3+final*0.4
print(length(which(total<60)))
print(x[which(total<60),1])
```

```{r}
x=1:5
x
x=seq(length=6,from=0,by=3)
x
x=seq(0,10,by=12)
x
```

```{r}
x=1:3
y=rep(x,times=2)
y
y=rep(x,each=2)
y

```

```{r}
x=c("4","2","8","A","B","C")
y=as.integer(x)
z = na.omit(y)
z
# y[is.na(y)]=0
# y
# mean(y,na.rm=T)
mean(y,na.rm=T)

```

```{r}
y=1:99
y
x=matrix(1:6,nrow=2,ncol=3)
x
x=matrix(1:6,nrow=2,ncol=3,byrow=T)
x
x=matrix(1:5,nrow=2,ncol=3,byrow=T)
x
x=matrix(1:6,nrow=2,ncol=3,byrow=F)
x
y=matrix(1:6,nrow = 3,ncol=2,byrow = T)
dim(x)=c(3,2)
x
```

```{r}
x=c(1:6)
dim(x)=c(2,3)
x
#by col
x=c(1:6)
dim(x)=c(3,2)
t(x)


```

```{r}
x=matrix(1:6,nrow=2,ncol=3)
x
x[2,]
x[,1]
x[1:2,2:3]
x[c(1,2),c(2,3)]
```

```{r}
x=matrix(1:6,nrow=2,ncol=3)
rownames(x)=paste("r",1:nrow(x),sep="-")
colnames(x)=paste("c",1:ncol(x),sep="-")
x
```

```{r}
x=matrix(1:6,nrow=2,ncol=3,byrow=T)
y=matrix(7:12,nrow=2,ncol=3,byrow=T)
cbind(x,y)
rbind(x,y)
```

腦筋急轉彎

```{r}
1:9%*%t(1:9)
```

```{r}
apply(iris[,1:4],2,mean)#1是row 2是col
```

練習

```{r}
x=read.csv("Week 2/finalscore_exercise.csv",sep=",",header=T)
apply(x[,2:4],2,mean)
apply(x[,2:4],2,sd)
apply(x[,2:4],2,mean)
apply(x[,2:4],2,sd)
```

```{r}
x=read.csv("Week 2/PM25.csv",sep=",",header=T)
x[is.na(x)]=0
target=apply(x[,3:ncol(x)],1,mean,na.rm=T)
names(target)=x[,1]
target

```
```{R}

x = list(A=c(1,2,3), B=matrix(c("a", "b", "c", "d"),nrow=2,ncol=2))
x = c(x, list(C=c(4,5,6)))

# 更改索引名稱
names(x)=c("a","b","c")
```
