```{R}
a=c(1,2,3)
a
names(a)=c("a","b","c")
a
a[2]
unname(a[2])
```

```{r}
x=c(1,2,3,4)
y=c(5,6,7,8)
x*y
y=c(5,6,7,4,3,2,1)
x*y
2*x+1
```

```{r}
x=c(3,1,2,1,1,4)
names(x)=c("A","B","C","D","E","F")
x==1
which(x==1)
unique(x)
sort(x)
order(x,)
```

練習

```{r}
x=read.csv("Week 2/finalscore_exercise.csv",sep=",",header=T)
hw=x[,2]
mid=x[,3]
final=x[,4]
total=hw*0.3+mid*0.3+final*0.4
names(total)=x[,1]
print(paste("Num of fail :",length(total<60)))
print(paste("Failed students"))
print(names(total)[which(total < 60)])
```

```{r}
x=1:5
x
x=seq(length=6,from=0,by=1)
x
x=seq(0,10,by=2)
x
```

```{r}
x=1:3
y=rep(x,times=2)
y
y=rep(x,each=2)
y

```

```{r}
x=c("4","2","8","A","B","C")
y=as.integer(x)
z = na.omit(y)
z
y[is.na(y)]=0
y
mean(y,na.rm=T)

```

```{r}
x=matrix(1:6,nrow=2,ncol=3)
x
x=matrix(1:6,nrow=2,ncol=3,byrow=T)
x
x=matrix(1:5,nrow=2,ncol=3,byrow=T)
x
```

```{r}
x=c(1:6)
dim(x)=c(2,3)
x
#by col
x=c(1:6)
dim(x)=c(3,2)
t(x)


```

```{r}
x=matrix(1:6,nrow=2,ncol=3)
x
x[2,]
x[,1]
x[1:2,2:3]
x[c(1,2),c(2,3)]
```

```{r}
x=matrix(1:6,nrow=2,ncol=3)
rownames(x)=paste("r",1:nrow(x),sep="-")
colnames(x)=paste("c",1:ncol(x),sep="-")
x
```

```{r}
x=matrix(1:6,nrow=2,ncol=3,byrow=T)
y=matrix(7:12,nrow=2,ncol=3,byrow=T)
cbind(x,y)
rbind(x,y)
```

腦筋急轉彎

```{r}
1:9%*%t(1:9)
```

```{r}
apply(iris[,1:4],2,mean)#1是row 2是col
```

練習

```{r}
x=read.csv("Week 2/finalscore_exercise.csv",sep=",",header=T)
apply(x[,2:4],2,mean)
apply(x[,2:4],2,sd)
apply(x[,2:4],1,mean)
apply(x[,2:4],1,sd)
```

```{r}
x=read.csv("Week 2/PM25.csv",sep=",",header=T)
a=apply(x[,3:26],1,mean,na.rm=T)
names(a)=x[,1]
a

```
